name: Stable OS 8

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "0 0 1 * *"   
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v4

    - name: Build and upload stable .iso
      run: |
        ./workflows.sh etc/terraform-stable-8.0-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}"
      env:
        OUTPUT_DIR: /path/to/output  # 确保这个路径是你的ISO文件生成的路径
        FNAME: elementaryos-stable-8.0  # 确保这个变量符合你的ISO文件命名规则

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: stable-os-8-iso
        path: ./builds/amd64/elementaryos-8.0-stable.20241125rc.iso
      if: success()  # 只有当构建成功时才上传artifacts
